[project]
name = "bookstring"
version = "0.0.0"
description = "Open-source reading progress tracker and social media website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.136.3",
    "lxml>=6.1.1",
    "mistletoe>=1.5.1",
    "typer>=0.26.7",
]

[project.scripts]
cli = "cli.main:__main__"

[dependency-groups]
dev = [
    "lxml-stubs>=0.5.1",
]
